version: '2'

services:
  presslabs-example:
    extends:
      file: docker-compose-base.yaml
      service: wordpress
    depends_on:
      - db
      - memcached
    volumes:
      - ../:/app
    environment:
      WP_ENV: development

  db:
    extends:
      file: docker-compose-base.yaml
      service: db

  memcached:
    extends:
      file: docker-compose-base.yaml
      service: memcached

volumes:
  db_data: {}
